### ISSUE TITLE
Outcomes not preserved across requests when iterations form has validation errors

### ISSUE THREAD

**Issue by suninthesky** [TechforgoodCAST/fusebox-insights#173]
To replicate:

1. New iteration
2. Add outcomes but leave title blank
3. Click 'Save as draft' or 'Commit to iteration'

**Comment by jdudley1123** [comment]
Looks like this issue is caused by this line: 
https://github.com/TechforgoodCAST/fusebox-insights/blob/775cbfaf93fd6dcc21baeb7b0d4c6b4972df4a32/app/views/iterations/_form.html.erb#L13

(per https://github.com/nathanvda/cocoon/issues/405#issuecomment-435371706)

Is there any reason we need an ordering method in there while it's still in draft state? Everything seems to work find if I remove it.

**Comment by suninthesky** [comment]
Good find. Up to you, `sort_by` or removing in draft works - I'd probably try `sort_by` first.
